### ISSUE TITLE
Can the author provide a grey Orange theme

### ISSUE THREAD

**Issue by jahnli** [ctwhome/webstorm-monokai-vscode-theme#1]
Can the author provide a grey Orange theme
[grey_orange.zip](https://github.com/ctwhome/webstorm-monokai-vscode-theme/files/5382156/grey_orange.zip)

**Comment by ctwhome** [comment]
thanks for the suggestion, it can be an interesting idea, but as for now I don't have plan to include other themes. However it is possible to modify the theme by following the instructions on the readme of this project. PR welcome!
